


### FIXME: USER
### register
POST http://localhost:5000/api/users/ HTTP/1.1
content-type: application/json

{
    "email": "admin@admin.com",
    "password": "123123",
    "name": "Admin"
}

### user login
POST http://localhost:5000/api/users/login HTTP/1.1
content-type: application/json

{
    "email": "admin@admin.com",
    "password": "123123"
}

### get user profile
GET http://localhost:5000/api/users/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzNhMDUyZjhiZDQwMTNhYzlhY2RmOSIsImlhdCI6MTYxODE5MDQzOCwiZXhwIjoxNjIwNzgyNDM4fQ.qapndO3kbtG1BUxFC8_3JGxbx5GDMc0lkdYqVP1hslg

### get user by id
GET http://localhost:5000/api/users/profile/6073a052f8bd4013ac9acdf9 HTTP/1.1

### update user profile
PUT http://localhost:5000/api/users/profile HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzNhMDUyZjhiZDQwMTNhYzlhY2RmOSIsImlhdCI6MTYxODE5MDQzOCwiZXhwIjoxNjIwNzgyNDM4fQ.qapndO3kbtG1BUxFC8_3JGxbx5GDMc0lkdYqVP1hslg

{
    "email": "user@admin.com",
    "name": "User Two"
}

### get all users :admin
GET http://localhost:5000/api/users/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzNhMDUyZjhiZDQwMTNhYzlhY2RmOSIsImlhdCI6MTYxODE5NDIzMCwiZXhwIjoxNjIwNzg2MjMwfQ.ZM_OmptPJgXW7AliEHS3U1suHSAFL9Mg_d95-P3Mpkg

### FIXME: POSTS
### get post by id
GET http://localhost:5000/api/posts/606fb03dbac5270a44fecda5 HTTP/1.1

### get all posts
GET http://localhost:5000/api/posts HTTP/1.1

### get all posts by :userId
GET http://localhost:5000/api/posts/6073aac55e31fb1f64086868

### delete post by id
DELETE http://localhost:5000/api/posts/60733f98f8ebae21ac6acccf HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNmZiMDNkYmFjNTI3MGE0NGZlY2RhNCIsImlhdCI6MTYxODE2NTU1NywiZXhwIjoxNjIwNzU3NTU3fQ.rQadWm8M-7C8mDi36aeB9iAwuUYKOBxU6-CXOCy1UII

### FIXME: COMMENTS
POST http://localhost:5000/api/comments/6073aac55e31fb1f64086868 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzNhMDUyZjhiZDQwMTNhYzlhY2RmOSIsImlhdCI6MTYxODE5MDQzOCwiZXhwIjoxNjIwNzgyNDM4fQ.qapndO3kbtG1BUxFC8_3JGxbx5GDMc0lkdYqVP1hslg

{
    "content": "testando"
}

### get comment by id
GET http://localhost:5000/api/comments/6073ad71d9410405a463eccf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzNhMDUyZjhiZDQwMTNhYzlhY2RmOSIsImlhdCI6MTYxODE5MDQzOCwiZXhwIjoxNjIwNzgyNDM4fQ.qapndO3kbtG1BUxFC8_3JGxbx5GDMc0lkdYqVP1hslg

### delete comment by id
DELETE http://localhost:5000/api/comments/6073ad36909e5e128038dbb4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzNhMDUyZjhiZDQwMTNhYzlhY2RmOSIsImlhdCI6MTYxODE5MDQzOCwiZXhwIjoxNjIwNzgyNDM4fQ.qapndO3kbtG1BUxFC8_3JGxbx5GDMc0lkdYqVP1hslg
#### const order = await Order.findById(req.params.id).populate('user', 'name email')