### get post by id

GET http://localhost:5000/api/posts/606fb03dbac5270a44fecda5 HTTP/1.1



# Authorization: Bearer xxx

### user login
POST http://localhost:5000/api/users/login HTTP/1.1
content-type: application/json

{
    "email": "jane@admin.com",
    "password": "123123"
}

### get user profile
GET http://localhost:5000/api/users/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNmZiMDNkYmFjNTI3MGE0NGZlY2RhNCIsImlhdCI6MTYxODE0MTk0MywiZXhwIjoxNjIwNzMzOTQzfQ.wjYa2AExdCIdOr7FYmVTGew8wHs-3uDrkYlJ6sWwraM


### get user by id
GET http://localhost:5000/api/users/profile/606fb03dbac5270a44fecda4 HTTP/1.1

### register
POST http://localhost:5000/api/users/ HTTP/1.1
content-type: application/json

{
    "email": "user@admin.com",
    "password": "123123",
    "name": "User One"
}

### update user profile
PUT http://localhost:5000/api/users/profile HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzJlMzJhYTIyOGY0MzA4MDE1ODg4YyIsImlhdCI6MTYxODE0MTk5NSwiZXhwIjoxNjIwNzMzOTk1fQ.OR1OA828COjRs5YnHCurQSOO6nYeNCqaMXDmo9b7iHo


{
    "email": "user@admin.com",
    "name": "User Two"
}

### get all users
GET http://localhost:5000/api/users/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNmZiMDNkYmFjNTI3MGE0NGZlY2RhMiIsImlhdCI6MTYxODE0MjIxMiwiZXhwIjoxNjIwNzM0MjEyfQ.wqctI4GLrPd6NyTLYZRb5klcKx3fO_y4azyuL_HlWc8

### get all posts
GET http://localhost:5000/api/posts HTTP/1.1

### delete post by id
DELETE http://localhost:5000/api/posts/60733f98f8ebae21ac6acccf HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNmZiMDNkYmFjNTI3MGE0NGZlY2RhNCIsImlhdCI6MTYxODE2NTU1NywiZXhwIjoxNjIwNzU3NTU3fQ.rQadWm8M-7C8mDi36aeB9iAwuUYKOBxU6-CXOCy1UII