### - - - - - - - - - - - - - - - - - - USER - - - - - - - - -- - - - - - - - -
### register
POST http://localhost:5000/api/users/ HTTP/1.1
content-type: application/json

{
    "email": "admin@admin.com",
    "password": "123123",
    "name": "Admin"
}

### user login
POST http://localhost:5000/api/users/login HTTP/1.1
content-type: application/json

{
    "email": "admin@admin.com",
    "password": "123123"
}

### get user profile FIXME
GET http://localhost:5000/api/users/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzNhMDUyZjhiZDQwMTNhYzlhY2RmOSIsImlhdCI6MTYxODE5MDQzOCwiZXhwIjoxNjIwNzgyNDM4fQ.qapndO3kbtG1BUxFC8_3JGxbx5GDMc0lkdYqVP1hslg

### get user by id
GET http://localhost:5000/api/users/profile/6077395725324b24ec80c2c2 HTTP/1.1

### update user profile
PUT http://localhost:5000/api/users/profile HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzNhMDUyZjhiZDQwMTNhYzlhY2RmOSIsImlhdCI6MTYxODE5MDQzOCwiZXhwIjoxNjIwNzgyNDM4fQ.qapndO3kbtG1BUxFC8_3JGxbx5GDMc0lkdYqVP1hslg

{
    "email": "user@admin.com",
    "name": "User Two"
}

### get all users :admin
GET http://localhost:5000/api/users/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzczOTU3MjUzMjRiMjRlYzgwYzJjMiIsImlhdCI6MTYxODUxOTMyNywiZXhwIjoxNjIxMTExMzI3fQ.BZIxgQMGvpehiCOgkx9_TGE1PnB0gnDfRyVLKNo2FPU

### add a new friend
POST http://localhost:5000/api/users/friend/60786d001a44ae0a98fd22b9 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzg2ZDAwMWE0NGFlMGE5OGZkMjJiOSIsImlhdCI6MTYxODUxNDY5MSwiZXhwIjoxNjIxMTA2NjkxfQ.KFRYV3j5L8kBxASlU4JFYJJZpjuYnZcG0_CjDEJEptM

{
    "userId": "6077395725324b24ec80c2c2"
}

### delete user
DELETE http://localhost:5000/api/users/607993bcaa84fa1da86bf6e5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzczOTU3MjUzMjRiMjRlYzgwYzJjMiIsImlhdCI6MTYxODUxOTMyNywiZXhwIjoxNjIxMTExMzI3fQ.BZIxgQMGvpehiCOgkx9_TGE1PnB0gnDfRyVLKNo2FPU

### - - - - - - - - - - - - - - - - - - POSTS - - - - - - - - -- - - - - - - - -
### get all posts
GET http://localhost:5000/api/posts HTTP/1.1

### get post by id
GET http://localhost:5000/api/posts/606fb03dbac5270a44fecda5 HTTP/1.1

### get all posts by :userId
GET http://localhost:5000/api/posts/my/60786d001a44ae0a98fd22b9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzg2ZDAwMWE0NGFlMGE5OGZkMjJiOSIsImlhdCI6MTYxODUxNDY5MSwiZXhwIjoxNjIxMTA2NjkxfQ.KFRYV3j5L8kBxASlU4JFYJJZpjuYnZcG0_CjDEJEptM

### delete post by id
DELETE http://localhost:5000/api/posts/6074525e8709f7147cf3bab8 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzQ1MGQ4NDk3MjJkMTIwOGY1YWJhZiIsImlhdCI6MTYxODI3NTg0MSwiZXhwIjoxNjIwODY3ODQxfQ.Hbgi7gPdNw_kVKI_Vq_pgQDCIrkLsKkI2Sa641OOyjE

### - - - - - - - - - - - - - - - - - - COMMENTS - - - - - - - - -- - - - - - - - -
### get all comments
GET http://localhost:5000/api/comments/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzczOTU3MjUzMjRiMjRlYzgwYzJjMiIsImlhdCI6MTYxODYwMzcxMywiZXhwIjoxNjIxMTk1NzEzfQ.h6w0DQndFmyNut9B9JX1Zt98U6N_G38JUTsJCxyHKaU

### post new comment
POST http://localhost:5000/api/comments/6073aac55e31fb1f64086868 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzNhMDUyZjhiZDQwMTNhYzlhY2RmOSIsImlhdCI6MTYxODE5MDQzOCwiZXhwIjoxNjIwNzgyNDM4fQ.qapndO3kbtG1BUxFC8_3JGxbx5GDMc0lkdYqVP1hslg

{
    "content": "testando"
}

### get comment by id
GET http://localhost:5000/api/comments/6073ad71d9410405a463eccf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzNhMDUyZjhiZDQwMTNhYzlhY2RmOSIsImlhdCI6MTYxODE5MDQzOCwiZXhwIjoxNjIwNzgyNDM4fQ.qapndO3kbtG1BUxFC8_3JGxbx5GDMc0lkdYqVP1hslg

### delete comment by id
DELETE http://localhost:5000/api/comments/6079edd0de2c781d80b4e205
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzQ1MGQ4NDk3MjJkMTIwOGY1YWJhZiIsImlhdCI6MTYxODI3NTg0MSwiZXhwIjoxNjIwODY3ODQxfQ.Hbgi7gPdNw_kVKI_Vq_pgQDCIrkLsKkI2Sa641OOyjE

### Search
GET http://localhost:5000/api/posts/search/filmes HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzRmMDc3ZDJmOGMzMzRlY2MxZGRhNyIsImlhdCI6MTYxODMzMTgyOSwiZXhwIjoxNjIwOTIzODI5fQ.Nq53Io_g5Y990Ndeyk8KEQ-tCqs7OOJLVkTQh8pcbd0

### avatar upload
POST http://localhost:5000/api/upload
content-type: application/json

{
    "image": "https"
}